language: cpp
sudo: required
dist: xenial

git:
  depth: 3

env:
  global:
    - COMPILE_ASIO=0

matrix:
  include:
    # linux with gcc 8
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    # linux with gcc 7
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    # linux with clang 7
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test  # for libstdc++
            - llvm-toolchain-xenial-7
          packages:
            - clang-7
            - libstdc++-8-dev
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7 && COMPILE_ASIO=1"
    # linux with clang 6.0
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test  # for libstdc++
            - llvm-toolchain-xenial-6.0
          packages:
            - clang-6.0
            - libstdc++-8-dev
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0 && COMPILE_ASIO=1"
    # osx with xcode10.1/clang
    - os: osx
      osx_image: xcode10.1

addons:
  apt:
    #update: true
    packages:
    - libasio-dev
    - qt5-default
    - libqt5opengl5-dev
    - libecasoundc-dev
    - doxygen
    - ecasound
    - libxml2-dev
    - libfftw3-dev
    - libsndfile1-dev
    - libjack-dev
    - libjack0
    - help2man
    - jackd1
    - pkg-config
    - libtool
  homebrew:
    #update: true
    packages:
    - asio
    - autoconf
    #- doxygen
    - ecasound
    - fftw
    - jack
    - liblo
    - libsndfile
    - libxml2
    - qt
    # using brew, it's not possible to install needed perl dependencies for
    # help2man (Locale::gettext), therefore best disabled for now
    #- help2man

before_script:
  - eval "${MATRIX_EVAL}"
  - ci/build-deps.sh
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/qt/lib/pkgconfig:/usr/local/lib/pkgconfig; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/qt/bin:$PATH"; fi
  - autoreconf -vfi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./configure; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./configure --prefix='/usr'; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make && sudo make install; fi

after_failure:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ls -alhv /usr/bin/ |grep -E "(clang|gcc|g\+\+)"; fi
  - if [[ -f config.log ]]; then cat config.log; fi

branches:
  only:
    - master
    - networking-with-osc
    - travis-integration

notifications:
  email: false
